/* 
  File:   main.cpp
  Author: Ian Huss
  Created on January 8, 2017, 11:13 AM
  Purpose: write a program that will predict how much the ECD will generate if 
 * the company makes $8,600,000 in sales this year.
 */

//System Libraries
#include <iostream>
using namespace std;

//Executable code begins here!!!
int main(int argc, char** argv) 
{
    //Declare Variables
    double sales_Percent, sales_Total, sales_Generated;
    //Input values
    sales_Percent = .58;
    sales_Total = 8.6E6;
    sales_Generated;
    //Process by mapping inputs to outputs
    sales_Generated = (sales_Percent * sales_Total);
    //Output values
    cout << " The total sales generated by the ECD is $" << sales_Generated 
            << " which is $4,988,000." << endl;
    //Exit stage right!
    return 0;
}